#
# BUILDER
#
FROM node:12.19.0 as build

WORKDIR /code

COPY package.json /code/package.json

RUN npm install --production

COPY . .
RUN npm run build

#
# PROD
#
FROM nginx as prod

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /code/build /usr/share/nginx/html

# CMD ["nginx", "-g", "daemon off;"]
