version: '3.8'

services:
  frontend:
    image: pmckee/crud-frontend:1.0.0
    build: 
      context: ./frontend
    ports:
      - "80:80"
    networks: 
      - frontend
      - backend
  
  backend:
    image: pmckee/crud-backend:1.0.0
    build:
      context: ./backend
    networks: 
      - backend

networks: 
  frontend:
  backend: