FROM node:12.19.0 as base
 
WORKDIR /code
 
COPY package.json package.json

############################################
#
#   D E V E L O P M E N T
#
FROM base as dev
 
RUN npm install
COPY . .
 
CMD [ "npm", "run", "start" ]

############################################
# 
#   T E S T
#
FROM base as test
 
CMD [ "npm", "run", "test" ]

############################################
#
#   P R O D U C T I O N 
#
FROM base as prod

RUN npm install --production
COPY . .
 
CMD [ "node", "server.js" ]